# Generated by Django 3.2.9 on 2022-01-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='prodid',
        ),
    ]
