# Generated by Django 3.2.9 on 2022-01-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220126_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
