# Generated by Django 3.2.9 on 2022-02-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220201_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodcatagory',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
