# Generated by Django 3.2.9 on 2022-03-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_ispremium_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='latitude',
            field=models.FloatField(default=None, null=True, verbose_name='location latitude'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='longitude',
            field=models.FloatField(default=None, null=True, verbose_name='location longitude'),
        ),
    ]
